#!/usr/bin/env node

const core = require('@actions/core');
const github = require('@actions/github');

async function run() {
  try {
    const token = core.getInput('github-token', { required: true });
    const baseUrl = process.env.OPENAI_BASE_URL || 'http://localhost:3001/v1';
    const apiKey = process.env.OPENAI_API_KEY;

    if (!apiKey) {
      core.setFailed('OPENAI_API_KEY is required');
      return;
    }

    const context = github.context;
    const pr = context.payload.pull_request;

    if (!pr) {
      core.setFailed('This action only works on pull requests');
      return;
    }

    // 获取 PR diff
    const diffUrl = pr.diff_url;
    core.info(`Fetching diff from: ${diffUrl}`);

    const diffResponse = await fetch(diffUrl);
    const diff = await diffResponse.text();

    if (!diff || diff.length === 0) {
      core.info('No diff available for review');
      return;
    }

    // 调用 AI 进行审查
    core.info('Sending diff to AI for review...');

    const aiResponse = await fetch(`${baseUrl}/chat/completions`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${apiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'kilo-auto',
        messages: [
          {
            role: 'system',
            content: 'You are an expert code reviewer. Analyze the following PR diff and provide: 1) Summary of changes, 2) Potential issues or bugs, 3) Security concerns, 4) Performance implications, 5) Suggestions for improvement. Be concise and actionable.',
          },
          {
            role: 'user',
            content: `Review this PR diff:\n\n${diff}`,
          },
        ],
        temperature: 0.3,
        max_tokens: 2000,
      }),
    });

    const aiResult = await aiResponse.json();
    const review = aiResult.choices?.[0]?.message?.content || 'No review generated';

    // 发布评论
    const octokit = github.getOctokit(token);
    await octok.rest.issues.createComment({
      owner: context.repo.owner,
      repo: context.repo.repo,
      issue_number: pr.number,
      body: `## 🤖 AI Code Review\n\n${review}\n\n---\n*Generated by FreeLLMAPI • Model: kilo-auto*`,
    });

    core.info('AI review posted successfully');
    core.setOutput('review', review);
  } catch (error) {
    core.setFailed(error.message);
  }
}

run();
