#!/usr/bin/env node

const core = require('@actions/core');
const github = require('@actions/github');

async function run() {
  try {
    const token = core.getInput('github-token', { required: true });
    const baseUrl = process.env.OPENAI_BASE_URL || 'http://localhost:3001/v1';
    const apiKey = process.env.OPENAI_API_KEY;

    if (!apiKey) {
      core.setFailed('OPENAI_API_KEY is required');
      return;
    }

    const context = github.context;
    const { owner, repo } = context.repo;

    // 获取最近的活动
    const octokit = github.getOctokit(token);

    // 获取最近的 commits
    const commits = await octok.rest.repos.listCommits({
      owner,
      repo,
      per_page: 20,
      since: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    });

    // 获取开放的 issues
    const issues = await octok.rest.issues.listForRepo({
      owner,
      repo,
      state: 'open',
      per_page: 10,
    });

    // 获取开放的 PRs
    const prs = await octok.rest.pulls.list({
      owner,
      repo,
      state: 'open',
      per_page: 10,
    });

    // 构建活动摘要
    const commitsText = commits.data
      .map(c => `${c.sha.substring(0, 7)} - ${c.commit.message.split('\n')[0]} (@${c.commit.author.name})`)
      .join('\n');

    const issuesText = issues.data
      .filter(i => !i.pull_request)
      .map(i => `#${i.number}: ${i.title} (${i.state})`)
      .join('\n');

    const prsText = prs.data
      .map(p => `#${p.number}: ${p.title} (@${p.user.login})`)
      .join('\n');

    // 调用 AI 生成摘要
    core.info('Generating daily summary with AI...');

    const aiResponse = await fetch(`${baseUrl}/chat/completions`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${apiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'kilo-auto',
        messages: [
          {
            role: 'system',
            content: 'You are a project manager assistant. Analyze the following daily activity and provide a concise summary with key highlights, action items, and priorities.',
          },
          {
            role: 'user',
            content: `Daily Activity Report:\n\nRecent Commits:\n${commitsText || 'No commits'}\n\nOpen Issues:\n${issuesText || 'No open issues'}\n\nOpen PRs:\n${prsText || 'No open PRs'}`,
          },
        ],
        temperature: 0.5,
        max_tokens: 1500,
      }),
    });

    const aiResult = await aiResponse.json();
    const summary = aiResult.choices?.[0]?.message?.content || 'No summary generated';

    // 创建或更新日报 issue
    const existingIssues = await octok.rest.issues.listForRepo({
      owner,
      repo,
      labels: 'ai-summary,daily-report',
      state: 'open',
      per_page: 1,
    });

    const today = new Date().toISOString().split('T')[0];
    const issueBody = `## 📊 Daily AI Summary - ${today}\n\n${summary}\n\n---\n*Auto-generated by AI Automation • Model: kilo-auto*`;

    if (existingIssues.data.length > 0) {
      await octok.rest.issues.update({
        owner,
        repo,
        issue_number: existingIssues.data[0].number,
        body: issueBody,
      });
      core.info(`Updated daily summary issue #${existingIssues.data[0].number}`);
    } else {
      await octok.rest.issues.create({
        owner,
        repo,
        title: `Daily AI Summary - ${today}`,
        body: issueBody,
        labels: ['ai-summary', 'daily-report'],
      });
      core.info('Created daily summary issue');
    }

    core.setOutput('summary', summary);
    core.info('Daily summary generated successfully');
  } catch (error) {
    core.setFailed(error.message);
  }
}

run();
